---
 - name: CAPTURE SHOW LICENSE STATUS
   dellos10_command:
     commands:
       - show license status
   register: output

 - name: DISPLAY THE OUTPUT
   debug: var=output.stdout

 - name: INSTALL TEXTFSM
   import_tasks: textfsm.yaml

 - name: PARSE THE OUTPUT for {{ ansible_network_os }} show_license_status
   textfsm_parser:
     src: "{{ lookup('file', './templates/{{ ansible_network_os }}_show_license_status.template') }}"
     content: "{{ output.stdout[0] }}"
     name: license_facts
   register: result
   vars:
     - ansible_network_os: dellos10
